# .pre-commit-config.yaml (minimal for 3-day sprint)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
#add nbstripout for Jupyter notebooks
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        name: Strip output from Jupyter notebooks
        entry: nbstripout --install --force

  # Security only
  # - repo: local
  #   hooks:
  #     - id: check-secrets
  #       name: Check for API tokens
  #       entry: bash -c 'grep -r "0b8f3c5ee57fc7dd376af28ae83e4c2c" . && exit 1 || exit 0'
  #       language: system
  #       pass_filenames: false
