version: '3.8'

services:
  risk-tool:
    build: .
    container_name: risk-tool
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./inference/outputs:/app/inference/outputs
    environment:
      - PYTHONPATH=/app/src
    networks:
      - risk-network

  # Optional: Web dashboard service
  dashboard:
    build: .
    container_name: risk-dashboard
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./inference/outputs:/app/inference/outputs
    environment:
      - PYTHONPATH=/app/src
    command: ["streamlit", "run", "scripts/trader_dashboard.py", "--server.address=0.0.0.0"]
    networks:
      - risk-network
    depends_on:
      - risk-tool

networks:
  risk-network:
    driver: bridge
