services:
  risk-tool:
    build: .
    container_name: risk-tool-app
    restart: unless-stopped
    volumes:
      # Mount database directory
      - ./data:/app/data
      # Mount logs directory
      - ./logs:/app/logs
      # Mount outputs directory
      - ./inference/outputs:/app/inference/outputs
      # Mount config files (read-only)
      - ./configs:/app/configs:ro
    env_file:
      - .env.docker
    environment:
      - TZ=UTC  # Change to your timezone
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - risk-tool-network

  # Optional: Streamlit dashboard service
  dashboard:
    build: .
    container_name: risk-tool-dashboard
    restart: unless-stopped
    command: ["streamlit", "run", "scripts/trader_dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data:ro
      - ./configs:/app/configs:ro
    env_file:
      - .env.docker
    depends_on:
      - risk-tool
    networks:
      - risk-tool-network
    profiles:
      - dashboard  # Only start when explicitly requested

networks:
  risk-tool-network:
    driver: bridge
