name: risk-tool
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.5.0
  - numpy>=1.24.0
  - scikit-learn>=1.3.0
  - lightgbm>=3.3.5
  - pyyaml>=6.0
  - jinja2>=3.1.0
  - joblib>=1.3.0
  - python-dotenv>=1.0.0
  - schedule>=1.2.0
  - pytz>=2023.3
  - pip
  - pip:
    - smtplib2>=0.2.1