trading:
  timezone: "US/Eastern"
  market_open: "09:30"
  email_time: "09:00"

model:
  global_model:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 6
    random_state: 42
  personal_model:
    min_trading_days: 30
    n_estimators: 50
    learning_rate: 0.1
    max_depth: 4
    random_state: 42
  ensemble:
    global_weight: 0.3
    personal_weight: 0.7

data:
  lookback_days: 252
  feature_windows: [5, 10, 20]
  holdout_months: 2

email:
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  from_email: ""  # Will use .env value
  password: ""    # Will use .env value
  to_emails: ["temurbekkhujaev@gmail.com"]

risk:
  high_risk_threshold: 0.7
  medium_risk_threshold: 0.5
