# Risk Management MVP Configuration

# Model parameters
model:
  min_training_days: 30
  validation_split: 0.2

# Feature engineering
features:
  rolling_windows: [3, 5, 10, 20]

# Risk thresholds
risk:
  high_loss_threshold: -1000
  medium_loss_threshold: 0
