# Trader Risk Management System Configuration

# Application settings
app:
  name: "Trader Risk Management System"
  version: "1.0.0"
  environment: "development"  # development, staging, production

# Data settings
data:
  database_path: "data/risk_tool.db"
  min_trading_days: 60
  test_cutoff_date: "2025-04-01"

# Feature engineering settings
features:
  # EWMA parameters
  ewma_spans: [5, 20]

  # Lag parameters
  lag_days: [1, 2, 3]

  # Feature groups
  basic_features:
    - "pnl"
    - "win_rate"
    - "trade_count"
    - "consecutive_wins"
    - "consecutive_losses"

  advanced_features:
    - "max_drawdown"
    - "volatility"
    - "sharpe_ratio"
    - "avg_win_loss_ratio"

  # Time windows for calculations
  rolling_windows:
    short: 5
    medium: 20
    long: 60

# Model settings
models:
  # XGBoost parameters
  xgboost:
    n_estimators: 200
    max_depth: 4
    learning_rate: 0.1
    objective: "multi:softprob"
    eval_metric: "mlogloss"
    random_state: 42
    n_jobs: -1

  # LightGBM parameters (alternative)
  lightgbm:
    n_estimators: 200
    max_depth: 4
    learning_rate: 0.1
    objective: "multiclass"
    metric: "multi_logloss"
    random_state: 42
    n_jobs: -1

  # Target classification
  target:
    loss_percentile: 25
    win_percentile: 75

  # Model selection
  active_model: "xgboost"

# Backtesting settings
backtesting:
  initial_train_size: 120  # days
  test_size: 30  # days
  min_train_size: 60  # days
  stride: 7  # days between retraining

# Trading strategies
strategies:
  # Position sizing strategy
  position_sizing:
    high_risk_reduction: 0.5  # 50% reduction
    low_risk_increase: 1.2   # 20% increase
    enabled: false

  # Trade filtering strategy
  trade_filtering:
    skip_high_risk_days: true
    enabled: true

  # Combined strategy
  combined:
    enabled: false

# Signal generation
signals:
  # Risk levels
  risk_levels:
    high: 2
    neutral: 1
    low: 0

  # Thresholds
  confidence_threshold: 0.6

  # Output settings
  output_format: "json"
  output_path: "outputs/signals"

# Monitoring and alerts
monitoring:
  # Performance thresholds
  min_accuracy: 0.4
  max_consecutive_errors: 5

  # PnL thresholds
  max_negative_impact_pct: 0.1  # 10%

  # Alert settings
  alert_channels:
    - "email"
    - "slack"

  # Monitoring intervals
  check_interval_minutes: 60

# Logging settings
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "json"

  # Log files
  handlers:
    file:
      enabled: true
      path: "outputs/logs/risk_management.log"
      max_bytes: 10485760  # 10MB
      backup_count: 5

    console:
      enabled: true

    # Production logging to external service
    external:
      enabled: false
      service: "datadog"  # datadog, splunk, elasticsearch
      api_key: "${LOGGING_API_KEY}"

# API settings
api:
  host: "0.0.0.0"
  port: 8000
  workers: 4

  # Security
  api_key_required: true
  cors_origins: ["*"]

  # Rate limiting
  rate_limit:
    enabled: true
    requests_per_minute: 60

# Deployment settings
deployment:
  # Model storage
  model_storage:
    type: "local"  # local, s3, gcs
    path: "outputs/models"

  # Model versioning
  versioning:
    enabled: true
    max_versions: 5

  # Health checks
  health_check:
    endpoint: "/health"
    timeout_seconds: 30

# Database settings
database:
  # Connection pool
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30

  # Backup settings
  backup:
    enabled: true
    schedule: "daily"
    retention_days: 30
    path: "data/backups"

# Feature flags
feature_flags:
  enable_advanced_features: true
  enable_real_time_signals: false
  enable_model_retraining: true
  enable_a_b_testing: false

# Paths (relative to project root)
paths:
  data_dir: "data"
  models_dir: "outputs/models"
  reports_dir: "outputs/reports"
  logs_dir: "outputs/logs"
  signals_dir: "outputs/signals"
  config_dir: "config"
