# config/risk_limits.yaml
risk_limits:
  daily:
    max_loss_pct: 0.02
    warning_loss_pct: 0.015
    max_trades: 50
  
  portfolio:
    max_exposure: 100000
    max_concentration: 0.1
    var_confidence: 0.95
  
  position:
    max_position_size: 10000
    kelly_fraction_limit: 0.25
    min_liquidity_ratio: 0.1

alerts:
  email:
    enabled: true
    recipients: ["trader@company.com"]
  
  slack:
    enabled: false
    webhook_url: ""
  
  severity_levels:
    - "INFO"
    - "WARNING" 
    - "CRITICAL"