traders:
  - account_id: 4766
    name: "NETS012_OLD"
    strategy: "Day Trading"
  - account_id: 6973
    name: "NECS008OP_OLD"
    strategy: "Day Trading"
  - account_id: 4003
    name: "NEL004_OLD"
    strategy: "Day Trading"
  - account_id: 5190
    name: "NEO006MS_OLD"
    strategy: "Day Trading"
  - account_id: 3976
    name: "NEO004OP_OLD"
    strategy: "Day Trading"
# Add more trader accounts as needed
