traders:
  # - account_id: 4766
  #   name: "NETS012_OLD"
  #   strategy: "Day Trading"
  # - account_id: 6973
  #   name: "NECS008OP_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4003
  #   name: "NEL004_OLD"
  #   strategy: "Day Trading"
  # - account_id: 5190
  #   name: "NEO006MS_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3976
  #   name: "NEO004OP_OLD"
  #   strategy: "Day Trading"
# Add more trader accounts as needed
# NEO006
# NET009
# NET005
# NET010
# NET026
  - account_id: 3957
    name: "NEO006_OLD"
    strategy: "Day Trading"
  - account_id: 3950
    name: "NET009_OLD"
    strategy: "Day Trading"
  - account_id: 3946
    name: "NET005_OLD"
    strategy: "Day Trading"
  - account_id: 4004
    name: "NEL005_OLD"
    strategy: "Day Trading"
  - account_id: 3951
    name: "NET010_OLD"
    strategy: "Day Trading"
