traders:
  - account_id: 3946
    name: "NET005_OLD"
    strategy: "Day Trading"
  - account_id: 4004
    name: "NEL005_OLD"
    strategy: "Day Trading"
  - account_id: 3951
    name: "NET010_OLD"
    strategy: "Day Trading"
  - account_id: 3956
    name: "NET015_OLD"
    strategy: "Day Trading"
  - account_id: 3942
    name: "NET001_OLD"
    strategy: "Day Trading"
  - account_id: 3950
    name: "NET009_OLD"
    strategy: "Day Trading"
  - account_id: 3978
    name: "NEO006OP_OLD"
    strategy: "Day Trading"
  - account_id: 3957
    name: "NEO006_OLD"
    strategy: "Day Trading"
  - account_id: 5093
    name: "NET026_OLD"
    strategy: "Day Trading"




  # - account_id: 3989
  #   name: "NEC001_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3991
  #   name: "NEC003_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4795
  #   name: "NECS004OP_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4745
  #   name: "NECS004_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3992
  #   name: "NEL001_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4001
  #   name: "NEL002_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4003
  #   name: "NEL004_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4729
  #   name: "NEL006_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3973
  #   name: "NEO001OP_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3959
  #   name: "NEO001_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3974
  #   name: "NEO002OP_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3984
  #   name: "NEO002TE_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3962
  #   name: "NEO002_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3975
  #   name: "NEO003OP_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3985
  #   name: "NEO003TE_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3963
  #   name: "NEO003_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3976
  #   name: "NEO004OP_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3986
  #   name: "NEO004TE_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3960
  #   name: "NEO004_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3977
  #   name: "NEO005OP_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3987
  #   name: "NEO005TE_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3958
  #   name: "NEO005_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3982
  #   name: "NEO006TE_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4283
  #   name: "NEO007OP_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4280
  #   name: "NEO007_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4340
  #   name: "NEO008_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4341
  #   name: "NEO009_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3943
  #   name: "NET002_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3944
  #   name: "NET003_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3945
  #   name: "NET004_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3947
  #   name: "NET006_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3948
  #   name: "NET007_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3949
  #   name: "NET008_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3952
  #   name: "NET011_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3953
  #   name: "NET012_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3954
  #   name: "NET013_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3955
  #   name: "NET014_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4334
  #   name: "NET016_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4395
  #   name: "NET017_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4396
  #   name: "NET018_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4737
  #   name: "NET019_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4738
  #   name: "NET020_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4739
  #   name: "NET021_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3997
  #   name: "NETS001OP_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3967
  #   name: "NETS001_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4284
  #   name: "NETS002TE_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3968
  #   name: "NETS002_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4285
  #   name: "NETS003TE_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3969
  #   name: "NETS003_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4286
  #   name: "NETS004TE_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3970
  #   name: "NETS004_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4287
  #   name: "NETS005TE_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3971
  #   name: "NETS005_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4288
  #   name: "NETS006TE_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3972
  #   name: "NETS006_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4397
  #   name: "NETS007_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4639
  #   name: "NETS008OP_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4398
  #   name: "NETS008_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4404
  #   name: "NETS009_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4796
  #   name: "NETS011OP_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4797
  #   name: "NETS012OP_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4766
  #   name: "NETS012_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4798
  #   name: "NETS013OP_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4788
  #   name: "NETS013_OLD"
  #   strategy: "Day Trading"

  # - account_id: 4765
  #   name: "NETS011_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4744
  #   name: "NETS010_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4647
  #   name: "NETS007OP_OLD"
  #   strategy: "Day Trading"
  # - account_id: 4002
  #   name: "NEL003_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3983
  #   name: "NEO001TE_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3964
  #   name: "NECS001_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3965
  #   name: "NECS002_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3966
  #   name: "NECS003_OLD"
  #   strategy: "Day Trading"
  # - account_id: 3990
  #   name: "NEC002_OLD"
  #   strategy: "Day Trading"
