# configs/main_config.yaml
paths:
  db_path: "data/risk_tool.db"  # SQLite database path
  raw_data: "data/risk_tool.db"  # Alias for backwards compatibility
  processed_features: "data/processed/trader_splits/"
  model_dir: "models/trader_specific/"
  report_dir: "reports/"

# Active traders list based on filtering criteria
active_traders: [3942, 3943, 3946, 3950, 3951, 3956, 4003, 4004, 4396, 5093, 5580]

feature_params:
  # Base EWMA and Rolling features
  ewma_spans: [3, 7, 21]
  rolling_vol_windows: [7, 21]
  # Advanced Risk features
  sortino_window: 21
  drawdown_window: 21
  profit_factor_window: 21
  # Behavioral feature lookback
  large_loss_lookback: 21  # days to look back for a 'large loss' to flag revenge trading

target_variable_params:
  large_loss_quantile: 0.15  # Defines a 'bad day'

# Walk-Forward Backtesting Configuration
backtesting:
  n_splits: 5  # Number of folds for the backtest
  train_days: 126  # Approx. 6 months of trading days (21*6)
  test_days: 21  # Approx. 1 month of trading days
  gap_days: 1  # Gap between train and test to prevent short-term leakage

# Final Production Model parameters
production_model:
  var_model:
    objective: "quantile"
    alpha: 0.05
    n_estimators: 100
    learning_rate: 0.05
    max_depth: 5
    num_leaves: 31
    min_child_samples: 20
    subsample: 0.8
    colsample_bytree: 0.8
    reg_alpha: 0.0  # L1 regularization
    reg_lambda: 0.0  # L2 regularization
    random_state: 42
  loss_model:
    objective: "binary"
    is_unbalance: true
    n_estimators: 100
    learning_rate: 0.05
    max_depth: 5
    num_leaves: 31
    min_child_samples: 20
    subsample: 0.8
    colsample_bytree: 0.8
    reg_alpha: 0.0  # L1 regularization
    reg_lambda: 0.0  # L2 regularization
    random_state: 42

# Model Quality and Validation Settings
model_quality:
  max_features: 15  # Maximum features to prevent overfitting
  enable_feature_selection: true
  early_stopping_rounds: 20
  validation_split: 0.2  # 20% for validation

  # Cross-validation settings (strict CV recommended)
  use_strict_cv: true   # Enable STRICT walk-forward CV with in-fold feature selection
  purge_days: 2         # Days to purge after training set (for purged CV)
  embargo_days: 1       # Additional embargo period (for purged CV)
  use_purged_cv: false  # Disable purged CV in favor of strict CV

  # Statistical validation thresholds
  thresholds:
    var_kupiec_p_value: 0.05  # Minimum p-value for VaR coverage test
    auc_stability_cv: 0.15    # Maximum coefficient of variation for AUC across folds
    feature_importance_concentration: 0.8  # Maximum concentration in top 5 features
    max_correlation: 0.8      # Maximum feature-target correlation to flag leakage

# Advanced Risk Metrics Configuration
advanced_metrics:
  enable_cvar: true
  cvar_alpha: 0.05  # Conditional VaR at 5% level
  multi_horizon: [1, 5, 21]  # Prediction horizons in days
  regime_detection: true

# Risk Classification Thresholds (for 4-level system)
risk_classification:
  use_weighted_formula: true
  alpha: 0.6  # Weight for VaR component
  beta: 0.4   # Weight for loss probability component
  thresholds:
    high_threshold: 0.35    # High risk: score >= 0.35
    medium_threshold: 0.22  # Medium risk: 0.22 <= score < 0.35
    low_threshold: 0.15     # Low risk: 0.15 <= score < 0.22
                           # Neutral: score < 0.15
  var_range: [-50000, 0]   # Range for VaR normalization
